import './globals.css'
import type { Metadata } from 'next'
import React, {ReactNode} from 'react'
import Header from './header'

export const metadata: Metadata = {
  title: 'Prototipe',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: ReactNode}) {
  return (
    <html lang="pt-BR">
      <body className="bg-gradient-to-br from-yellow-300 to-yellow-500">
        <Header />
        {children}
        </body>
    </html>
  )
}
